/*
 * generated by Xtext 2.24.0
 */
package ime.xtext.radioDsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
