/*
 * generated by Xtext 2.24.0
 */
package ime.xtext.radioDsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ime/xtext/radioDsl/parser/antlr/internal/InternalDsl.tokens");
	}
}
