/*
 * generated by Xtext 2.24.0
 */
package ime.xtext.radioDsl.ui.tests;

import com.google.inject.Injector;
import ime.xtext.radioDsl.ui.internal.RadioDslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RadioDslActivator.getInstance().getInjector("ime.xtext.radioDsl.Dsl");
	}

}
