/*
 * generated by Xtext 2.24.0
 */
package ime.xtext.radioDsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ime.xtext.radioDsl.DslRuntimeModule;
import ime.xtext.radioDsl.DslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslIdeSetup extends DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslRuntimeModule(), new DslIdeModule()));
	}
	
}
