/*
 * generated by Xtext 2.24.0
 */
package ime.xtext.radioDsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
